# This is a basic workflow that is manually triggered

name: CI
# on: [push, pull_request]

on:
   push:
   # pull_request_review:
   #  types:
   #    - submitted
jobs:
  check:
    if: ${{github.ref_name != 'main' && github.ref != null}}
    runs-on: self-hosted
    steps:
    - name: Check
      run: echo "=========ref_name=${{ github.ref_name}}, ref=${{ github.ref}}, base_ref=${{ github.base_ref}}, head_ref=${{ github.head_ref}}, ref_type=${{ github.ref_type}}"
  lint:
    if: ${{github.ref_name == 'main' && startsWith(github.event.head_commit.message, 'Merge pull request')}}
    runs-on: self-hosted
    steps:
      - name: lint
        run: echo "=========ref_name=${{ github.ref_name}}, ref=${{ github.ref}}, base_ref=${{ github.base_ref}}, head_ref=${{ github.head_ref}}, ref_type=${{ github.ref_type}}"
        # run: |
        #     /Users/shengjie/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/bin/bundle exec fastlane lint
  pub:
    if: ${{github.ref_name == 'main' && startsWith(github.event.head_commit.message, 'Merge pull request')}}
    runs-on: self-hosted
    needs: [lint]
    steps:
      - name: pub
        run: echo "${{ github.ref_name}}, ${{ github.ref}}, ${{ github.base_ref}}, ${{ github.head_ref}}, ${{ github.ref_type}}"
