# This is a basic workflow that is manually triggered

name: CI
# on: [push, pull_request]

on: [push]
#    push:
#        branches:
#          - '!main'
#    pull_request:
#        branches:
#          - 'main'
jobs:
  check:
    runs-on: self-hosted
    steps:
    - name: Check
      if: ${{github.ref_name != 'main' && github.ref != null}}
      run: echo "=========ref_name=${{ github.ref_name}}, ref=${{ github.ref}}, base_ref=${{ github.base_ref}}, head_ref=${{ github.head_ref}}, ref_type=${{ github.ref_type}}"
  lint:
    runs-on: self-hosted
    steps:
      - name: lint
        if: ${{github.ref_name == 'main'}}
        run: echo "=========ref_name=${{ github.ref_name}}, ref=${{ github.ref}}, base_ref=${{ github.base_ref}}, head_ref=${{ github.head_ref}}, ref_type=${{ github.ref_type}}"
        # run: |
        #     /Users/shengjie/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/bin/bundle exec fastlane lint
  # pub:
  #   if: ${{ github.base_ref == github.head_ref}}
  #   runs-on: self-hosted
  #   needs: [lint]
  #   steps:
  #   - name: pub
  #     run: echo "${{ github.ref_name}}, ${{ github.ref}}, ${{ github.base_ref}}, ${{ github.head_ref}}, ${{ github.ref_type}}"
